### ISSUE TITLE
print_annotation KeyError

### ISSUE THREAD

**Issue by turian** [RightTyper/RightTyper#14]
To profile the other major codepath I use, I changed a hydra config value. Now I get this issue:

```
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/torch312/lib/python3.12/site-packages/righttyper/righttyper.py", line 572, in output_type_signatures
    annotations = print_annotation(t)
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/torch312/lib/python3.12/site-packages/righttyper/righttyper_shapes.py", line 136, in print_annotation
    tups = transform_input(list(captured_shapes[func]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/torch312/lib/python3.12/site-packages/righttyper/righttyper_shapes.py", line 64, in transform_input
    output_vals[i][j] = symbolic_variable[hashes[i][j]]
                        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 4005882147695576827
```

**Comment by emeryberger** [comment]
If you can provide a [minimal working example](https://en.wikipedia.org/wiki/Minimal_reproducible_example), that would be ideal.

**Comment by emeryberger** [comment]
Ping @turian

**Comment by emeryberger** [comment]
Can't reproduce, closing for lack of response.
